//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.18 at 03:13:51 PM EAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://techprimers.com/soap-webservice-example", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.techprimers.soap_webservice_example;
